#!/bin/sh
set -efu

echo "ERROR: Adapt this autopkgtests script to the package and remove this line" ; exit 1

pys="$(py3versions -r 2> /dev/null)"

cp -a tests "$AUTOPKGTEST_TMP"
cd "$AUTOPKGTEST_TMP"

for py in $pys; do
  echo "=== $py ==="
  $py -m pytest tests 2>&1
done
